name: MobileFunctionBlock
version: '1.0'
main: org.hukm.mobilefunctionblocks.MobileFunctionBlock
api-version: '1.20'
commands:
  giveitems:
    description: "Выдает переносимые функциональные блоки"
depend: [api]